name: CI

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * * # every day at midnight

env:
  FORCE_COLOR: true
  NODE_VERSION: 20

jobs:
  setup:
    name: Test & Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: pnpm install

      - name: Generate GraphQL Types
        run: pnpm generate

      - name: Run Linter
        run: pnpm lint

      - name: Run Tests
        run: pnpm coverage

      - name: Commit new files
        if: success() && github.ref == 'refs/heads/develop'
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            pnpm document
            git config --global user.name "GitHub Actions"
            git config --global user.email ${{ secrets.GH_EMAIL }}
            git add .
            git commit -m "feat: update graphql types [skip ci]"
            git push origin HEAD:develop
          fi

      - name: Create Release
        if: success() && github.ref == 'refs/heads/develop'
        run: pnpm semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
